name: ImmortalWRT 24.10 Linux 6.6 Firmware mt_wifi driver (padavanonly)

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      repo_url: https://github.com/padavanonly/immortalwrt-mt798x-6.6.git
      repo_branch: openwrt-24.10-6.6
      config_file: config.immortalwrt-2410-6.6-padavanonly
      device_name: Flint2_GL-MT6000
      firmware_name: immortalwrt-2410-6.6-padavanonly
      source_dir: immortalwrt-mt798x-24.10
      kernel_version: 6.6
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
