name: ImmortalWRT 21.02 Firmware mt_wifi driver (hanwckf)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      repo_url: https://github.com/hanwckf/immortalwrt-mt798x.git
      repo_branch: openwrt-21.02
      config_file: config.immortalwrt-2102-hanwckf
      device_name: Flint2_GL-MT6000
      firmware_name: immortalwrt-2102-hanwckf
      source_dir: immortalwrt-mt798x
      kernel_version: 5.4
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
