name: TEST ImmortalWRT 24.10 Firmware mt_wifi driver (padavanonly)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      repo_url: https://github.com/padavanonly/immortalwrt-mt798x-24.10.git
      repo_branch: 2410
      config_file: config.test-padavanonly-24
      device_name: Flint2_GL-MT6000
      firmware_name: immortalwrt-2410-test-padavanonly
      source_dir: immortalwrt-mt798x-24.10
      patch_file: 903-fix-nft-reject-bridge.patch
      patch_target: target/linux/generic/backport-5.4
      kernel_version: 5.4
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
